version: '3.1'

services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: koe_engine
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: koe_forum_db
    ports:
        - '5432:5432'
    volumes: 
      - .db:/var/lib/postgresql